name: test

on:
  push:
    paths:
      - 'LuatOS_Downloader/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'LuatOS_Downloader/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: environment prepare
        run: |
          choco install dotnet --version 6.0.12 -y
          choco install dotnet-sdk --version 6.0.404 -y
      - name: test
        run: |
          wget https://github.com/LuatOS-Downloader/test-pack/releases/download/0.0.0/test-win_x64.zip
          unzip test-win_x64.zip
          cd LuatOS_Downloader
          dotnet test
